import { MetricData, LoadItem, CarrierItem, AlertItem, DocumentItem, ActivityEvent } from "./types";

export const initialKPIs: MetricData = {
  totalLoads: 10482,
  deliveredLoads: 9821,
  delayedLoads: 428,
  revenue: 842500,
  avgRevenuePerLoad: 80.37,
  onTimeDeliveryRate: 91.4,
  activeCarriers: 318,
  activeDrivers: 1642,
};

export const sampleLoads: LoadItem[] = [
  {
    id: "L10092",
    customer: "GlobalRetail Logistics",
    carrierId: "C-101",
    carrierName: "Atlas Freight",
    driverName: "James Carter",
    driverPhone: "+1 (555) 234-8901",
    origin: "Chicago, IL",
    destination: "Dallas, TX",
    distanceMiles: 924,
    revenue: 2850,
    loadType: "Dry Van",
    status: "High Risk",
    pickupTime: "2026-09-24 06:30",
    scheduledDeliveryTime: "2026-09-25 14:00",
    eta: "2026-09-25 17:45 (+3h 45m)",
    lateProbability: 0.82,
    riskLevel: "High",
    delayHours: 3.75,
    shapFactors: [
      { factor: "Pickup Departure Delay", impact: 0.31, description: "Departed shipper facility 2h 15m behind schedule due to loading dock queue" },
      { factor: "Carrier Historical Late Rate", impact: 0.22, description: "Atlas Freight late rate on I-55/I-30 corridor is 16.4% above benchmark" },
      { factor: "Corridor Weather / Traffic", impact: 0.14, description: "Severe thunderstorm warning around Little Rock, AR causing slowdowns" },
      { factor: "Driver Hours of Service", impact: -0.04, description: "Driver has 6.2 hours driving remaining before mandatory 10h rest" },
    ],
    timeline: [
      { stage: "Tender Accepted", time: "Sep 23, 18:00", completed: true },
      { stage: "Arrived at Pickup", time: "Sep 24, 06:15", completed: true },
      { stage: "Departed Shipper", time: "Sep 24, 08:45", completed: true, statusNote: "Delayed +2h 15m at dock" },
      { stage: "In Transit (I-30 Mile 114)", time: "Sep 25, 05:30", completed: true, statusNote: "Current speed 48 mph" },
      { stage: "Scheduled Delivery", time: "Sep 25, 14:00", completed: false, statusNote: "Predicted ETA 17:45" },
    ],
  },
  {
    id: "L10231",
    customer: "Apex Automotive Parts",
    carrierId: "C-104",
    carrierName: "Apex Carrier Systems",
    driverName: "Marcus Vance",
    driverPhone: "+1 (555) 782-3104",
    origin: "Detroit, MI",
    destination: "Nashville, TN",
    distanceMiles: 538,
    revenue: 1650,
    loadType: "Flatbed",
    status: "Delayed",
    pickupTime: "2026-09-24 10:00",
    scheduledDeliveryTime: "2026-09-25 08:00",
    eta: "2026-09-25 11:15 (+3h 15m)",
    lateProbability: 0.94,
    riskLevel: "Critical",
    delayHours: 3.25,
    shapFactors: [
      { factor: "Mechanical Maintenance Stop", impact: 0.44, description: "Flat tire inspection and roadside service near Cincinnati, OH" },
      { factor: "Shipper Detention", impact: 0.18, description: "Wait time at Detroit stamping plant exceeded allotted 2 hours" },
      { factor: "Route Density", impact: 0.08, description: "I-75 South construction bottlenecks" },
    ],
    timeline: [
      { stage: "Tender Accepted", time: "Sep 23, 21:00", completed: true },
      { stage: "Loaded at Shipper", time: "Sep 24, 12:45", completed: true },
      { stage: "Roadside Service", time: "Sep 24, 22:30", completed: true, statusNote: "Resolved after 2.5h" },
      { stage: "In Transit (I-75 Mile 182)", time: "Sep 25, 04:50", completed: true },
      { stage: "Consignee Delivery", time: "Sep 25, 08:00", completed: false, statusNote: "Revised ETA 11:15" },
    ],
  },
  {
    id: "L10021",
    customer: "FreshSource Produce",
    carrierId: "C-102",
    carrierName: "Northline Transport",
    driverName: "Elena Rostova",
    driverPhone: "+1 (555) 449-0129",
    origin: "Salinas, CA",
    destination: "Denver, CO",
    distanceMiles: 1120,
    revenue: 3400,
    loadType: "Reefer",
    status: "In Transit",
    pickupTime: "2026-09-23 16:00",
    scheduledDeliveryTime: "2026-09-25 20:00",
    eta: "2026-09-25 19:15 (-45m early)",
    lateProbability: 0.14,
    riskLevel: "Low",
    shapFactors: [
      { factor: "Early Pickup Execution", impact: -0.22, description: "Departed origin 30 minutes ahead of scheduled dispatch slot" },
      { factor: "Carrier Top Reliability", impact: -0.15, description: "Northline has a 96.8% on-time record on West Coast corridors" },
      { factor: "Mountain Pass Weather", impact: 0.05, description: "Clear conditions through Donner Pass and I-80" },
    ],
    timeline: [
      { stage: "Tender Accepted", time: "Sep 22, 14:00", completed: true },
      { stage: "Reefer Pre-Cooled (-4°F)", time: "Sep 23, 14:30", completed: true },
      { stage: "Departed Salinas", time: "Sep 23, 15:30", completed: true },
      { stage: "Passed Salt Lake City", time: "Sep 24, 18:00", completed: true },
      { stage: "Final Mile Denver", time: "Sep 25, 20:00", completed: false, statusNote: "Tracking on-time" },
    ],
  },
  {
    id: "L10419",
    customer: "Summit Chemical Corp",
    carrierId: "C-103",
    carrierName: "SwiftLink Logistics",
    driverName: "Darnell Washington",
    driverPhone: "+1 (555) 612-9934",
    origin: "Houston, TX",
    destination: "Atlanta, GA",
    distanceMiles: 790,
    revenue: 2600,
    loadType: "Hazmat",
    status: "In Transit",
    pickupTime: "2026-09-24 14:00",
    scheduledDeliveryTime: "2026-09-26 09:00",
    eta: "2026-09-26 08:30 (-30m)",
    lateProbability: 0.28,
    riskLevel: "Low",
    shapFactors: [
      { factor: "Hazmat Mandatory Route Restrictions", impact: 0.12, description: "Required bypass routes around major metro centers" },
      { factor: "Experienced Hazmat Driver", impact: -0.19, description: "Driver has 12 years certified hazmat record" },
    ],
    timeline: [
      { stage: "Placard Inspection Passed", time: "Sep 24, 12:00", completed: true },
      { stage: "Departed Houston", time: "Sep 24, 14:15", completed: true },
      { stage: "In Transit (I-10 E / I-65 N)", time: "Sep 25, 03:00", completed: true },
      { stage: "Atlanta Terminal Delivery", time: "Sep 26, 09:00", completed: false },
    ],
  },
  {
    id: "L10355",
    customer: "OmniPack Containers",
    carrierId: "C-105",
    carrierName: "Horizon Cargo",
    driverName: "David Lee",
    driverPhone: "+1 (555) 901-4472",
    origin: "Kansas City, MO",
    destination: "Indianapolis, IN",
    distanceMiles: 485,
    revenue: 1420,
    loadType: "Dry Van",
    status: "Delivered",
    pickupTime: "2026-09-24 07:00",
    scheduledDeliveryTime: "2026-09-24 19:00",
    eta: "2026-09-24 18:40 (-20m)",
    lateProbability: 0.05,
    riskLevel: "Low",
    timeline: [
      { stage: "Pickup Completed", time: "Sep 24, 07:15", completed: true },
      { stage: "In Transit", time: "Sep 24, 11:30", completed: true },
      { stage: "Delivered & Signed POD", time: "Sep 24, 18:40", completed: true },
    ],
  },
  {
    id: "L10118",
    customer: "Pioneer Medical Supply",
    carrierId: "C-101",
    carrierName: "Atlas Freight",
    driverName: "Robert Kovacs",
    driverPhone: "+1 (555) 321-7788",
    origin: "Minneapolis, MN",
    destination: "Columbus, OH",
    distanceMiles: 755,
    revenue: 2300,
    loadType: "Dry Van",
    status: "High Risk",
    pickupTime: "2026-09-24 18:00",
    scheduledDeliveryTime: "2026-09-25 16:30",
    eta: "2026-09-25 19:40 (+3h 10m)",
    lateProbability: 0.76,
    riskLevel: "High",
    delayHours: 3.16,
    shapFactors: [
      { factor: "Late Shipper Release", impact: 0.28, description: "Warehouse delayed release by 1h 50m awaiting QA release certificate" },
      { factor: "Chicago Tollway Congestion", impact: 0.19, description: "Peak rush hour traffic along I-90 / I-94" },
    ],
    timeline: [
      { stage: "Dispatched", time: "Sep 24, 16:00", completed: true },
      { stage: "Loaded", time: "Sep 24, 19:50", completed: true },
      { stage: "In Transit", time: "Sep 25, 05:10", completed: true },
      { stage: "ETA Columbus", time: "Sep 25, 19:40", completed: false },
    ],
  },
  {
    id: "L10502",
    customer: "BioNutrient Systems",
    carrierId: "C-106",
    carrierName: "PrimeHaul Freight",
    driverName: "Sarah Jenkins",
    driverPhone: "+1 (555) 887-1234",
    origin: "Memphis, TN",
    destination: "Charlotte, NC",
    distanceMiles: 615,
    revenue: 1950,
    loadType: "Dry Van",
    status: "Delivered",
    pickupTime: "2026-09-24 08:00",
    scheduledDeliveryTime: "2026-09-25 06:00",
    eta: "2026-09-25 05:45 (-15m)",
    lateProbability: 0.08,
    riskLevel: "Low",
    timeline: [
      { stage: "Pickup", time: "Sep 24, 08:05", completed: true },
      { stage: "Delivered", time: "Sep 25, 05:45", completed: true },
    ],
  },
  {
    id: "L10289",
    customer: "SteelWorks Industrial",
    carrierId: "C-107",
    carrierName: "Titan Trucking",
    driverName: "Bill Henderson",
    driverPhone: "+1 (555) 776-5512",
    origin: "Pittsburgh, PA",
    destination: "Louisville, KY",
    distanceMiles: 388,
    revenue: 1480,
    loadType: "Flatbed",
    status: "In Transit",
    pickupTime: "2026-09-25 02:00",
    scheduledDeliveryTime: "2026-09-25 15:00",
    eta: "2026-09-25 14:30 (-30m)",
    lateProbability: 0.18,
    riskLevel: "Low",
    timeline: [
      { stage: "Secured & Tarped", time: "Sep 25, 02:30", completed: true },
      { stage: "Rolling (I-70 W)", time: "Sep 25, 05:00", completed: true },
      { stage: "Scheduled Delivery", time: "Sep 25, 15:00", completed: false },
    ],
  },
];

export const sampleCarriers: CarrierItem[] = [
  {
    id: "C-101",
    name: "Atlas Freight",
    mcNumber: "MC-789210",
    totalLoads: 428,
    revenue: 842000,
    onTimeRate: 83.6,
    lateRate: 16.4,
    cancellationRate: 1.2,
    avgDeliveryHours: 28.4,
    rating: 3.8,
    status: "Under Review",
    trend: "down",
    sparklineData: [92, 90, 88, 87, 85, 84, 83.6],
  },
  {
    id: "C-102",
    name: "Northline Transport",
    mcNumber: "MC-451290",
    totalLoads: 391,
    revenue: 710000,
    onTimeRate: 94.2,
    lateRate: 5.8,
    cancellationRate: 0.4,
    avgDeliveryHours: 24.1,
    rating: 4.8,
    status: "Active",
    trend: "up",
    sparklineData: [90, 91, 92, 93, 93.5, 94, 94.2],
  },
  {
    id: "C-103",
    name: "SwiftLink Logistics",
    mcNumber: "MC-612049",
    totalLoads: 312,
    revenue: 590000,
    onTimeRate: 91.8,
    lateRate: 8.2,
    cancellationRate: 0.8,
    avgDeliveryHours: 26.0,
    rating: 4.5,
    status: "Active",
    trend: "neutral",
    sparklineData: [91, 92, 91.5, 91.8, 92, 91.5, 91.8],
  },
  {
    id: "C-104",
    name: "Apex Carrier Systems",
    mcNumber: "MC-882310",
    totalLoads: 284,
    revenue: 495000,
    onTimeRate: 77.4,
    lateRate: 22.6,
    cancellationRate: 3.1,
    avgDeliveryHours: 32.2,
    rating: 3.2,
    status: "Under Review",
    trend: "down",
    sparklineData: [86, 84, 82, 80, 79, 78, 77.4],
  },
  {
    id: "C-105",
    name: "Horizon Cargo",
    mcNumber: "MC-319940",
    totalLoads: 260,
    revenue: 430000,
    onTimeRate: 96.1,
    lateRate: 3.9,
    cancellationRate: 0.3,
    avgDeliveryHours: 22.8,
    rating: 4.9,
    status: "Active",
    trend: "up",
    sparklineData: [94, 95, 95, 95.8, 96, 96.1, 96.1],
  },
  {
    id: "C-106",
    name: "PrimeHaul Freight",
    mcNumber: "MC-902114",
    totalLoads: 215,
    revenue: 380000,
    onTimeRate: 92.5,
    lateRate: 7.5,
    cancellationRate: 0.9,
    avgDeliveryHours: 25.4,
    rating: 4.4,
    status: "Active",
    trend: "neutral",
    sparklineData: [91, 91.5, 92, 92, 92.3, 92.5, 92.5],
  },
];

export const sampleAlerts: AlertItem[] = [
  {
    id: "ALT-401",
    type: "High Risk",
    severity: "critical",
    title: "Load L10092 Late Probability Exceeded 80%",
    entityId: "L10092",
    entityType: "load",
    reason: "82% ML late probability detected due to 2h 15m pickup delay and corridor storm warning.",
    timestamp: "12 min ago",
    resolved: false,
    actionLabel: "Inspect Load",
  },
  {
    id: "ALT-402",
    type: "Delayed Load",
    severity: "critical",
    title: "Load L10231 Roadside Delay on I-75",
    entityId: "L10231",
    entityType: "load",
    reason: "Mechanical maintenance stop caused a 3h 15m delay past scheduled delivery time.",
    timestamp: "38 min ago",
    resolved: false,
    actionLabel: "Notify Consignee",
  },
  {
    id: "ALT-403",
    type: "Carrier Drop",
    severity: "warning",
    title: "Apex Carrier Systems Performance Drop",
    entityId: "C-104",
    entityType: "carrier",
    reason: "On-time delivery declined by 8.6% this week (current 77.4%, threshold 85%).",
    timestamp: "1 hr ago",
    resolved: false,
    actionLabel: "Review Carrier",
  },
  {
    id: "ALT-404",
    type: "Automation",
    severity: "info",
    title: "n8n Daily Operations Summary Generated",
    entityId: "SYS-AUTO-01",
    entityType: "system",
    reason: "Automated workflow compiled metrics: 428 loads dispatched, $842.5K revenue, 91.4% on-time.",
    timestamp: "3 hrs ago",
    resolved: true,
    actionLabel: "View Report",
  },
];

export const sampleDocuments: DocumentItem[] = [
  {
    id: "DOC-SOP-01",
    title: "Carrier Breakdown & Roadside Assistance Protocol",
    category: "SOP",
    fileType: "pdf",
    pages: 14,
    updatedAt: "2026-09-15",
    summary: "Mandatory dispatcher procedures when a carrier reports mechanical malfunction or tire blowout.",
    content: "When a driver reports a breakdown: 1. Confirm driver safety and GPS location. 2. Verify cargo status (reefer temp / seal). 3. Contact carrier dispatch for authorized vendor ETA. 4. If delay exceeds 2 hours, notify consignee and log exception ticket in Metrix.",
    sections: [
      { heading: "Section 1: Initial Driver Contact", text: "Dispatcher must verify truck coordinates and safe parking off highway shoulder within 15 minutes of first notification.", page: 2 },
      { heading: "Section 2: Temperature Sensitive Cargo", text: "For refrigerated loads, continuous reefer telemetry must be documented every 30 minutes until tow or mobile repair completes.", page: 5 },
      { heading: "Section 3: Cross-Dock and Re-Power Contingency", text: "If repairs exceed 4 hours on high-value or perishable loads, emergency re-power truck must be requested from secondary carrier pool.", page: 9 },
    ],
  },
  {
    id: "DOC-SOP-02",
    title: "Shipper Missed Pickup & Late Dispatch SOP",
    category: "SOP",
    fileType: "md",
    pages: 6,
    updatedAt: "2026-09-02",
    summary: "Standard resolution steps when carrier fails to arrive at shipper facility within 60-minute appointment grace window.",
    content: "If carrier has not arrived 30 minutes prior to appointment, dispatcher must initiate automated ping. At +60 minutes, carrier is deemed Missed Pickup and recovery options must be triggered.",
    sections: [
      { heading: "1.0 Grace Period Window", text: "Standard shipper facilities grant a 60-minute grace window before releasing dock reservation to standby carriers.", page: 1 },
      { heading: "2.0 Carrier TONU & Recovery Protocol", text: "If load is recovered by another carrier, original tender is revoked with cause. No TONU fee is payable for missed appointment.", page: 3 },
    ],
  },
  {
    id: "DOC-SOP-03",
    title: "Reefer Temperature Excursion & Cold-Chain Protocol",
    category: "Compliance",
    fileType: "pdf",
    pages: 22,
    updatedAt: "2026-08-20",
    summary: "FDA Food Safety Modernization Act (FSMA) compliance requirements for temperature controlled freight.",
    content: "Continuous automated temperature monitoring required. Any temperature deviation greater than +/- 3 degrees Fahrenheit lasting over 45 minutes constitutes an excursion requiring immediate QA quarantine.",
    sections: [
      { heading: "Section 4: Sensor Calibration & Logging", text: "Reefer downloading of electronic data logs required prior to unsealing trailer doors at delivery facility.", page: 8 },
      { heading: "Section 7: Cargo Quarantine Procedure", text: "Receiving dock manager must not break seal if temperature alarm is flagged on the bill of lading.", page: 14 },
    ],
  },
  {
    id: "DOC-SOP-04",
    title: "Shipper & Receiver Detention Billing Policy",
    category: "Policy",
    fileType: "txt",
    pages: 4,
    updatedAt: "2026-09-10",
    summary: "Terms and billing procedures for driver detention exceeding the standard 2-hour free time.",
    content: "Detention rate is $65.00/hour billed in 15-minute increments following the initial 120 minutes of confirmed on-site driver presence via geofence timestamp.",
    sections: [
      { heading: "Article 1: Geofence Verification", text: "Driver must establish verified GPS geofence arrival within 200 feet of facility perimeter to start free time clock.", page: 1 },
      { heading: "Article 3: Required Supporting Documentation", text: "Signed Bills of Lading with legible in/out time stamps required for customer invoice submission.", page: 2 },
    ],
  },
];

export const sampleActivityFeed: ActivityEvent[] = [
  {
    id: "EV-01",
    time: "09:42",
    type: "risk",
    title: "Load L10092 entered high-risk state",
    description: "ML risk score calculated at 82% late probability due to pickup delay and corridor thunderstorm.",
  },
  {
    id: "EV-02",
    time: "09:38",
    type: "carrier",
    title: "Carrier Apex Systems crossed delay threshold",
    description: "On-time rate fell below 80% across 284 completed loads.",
  },
  {
    id: "EV-03",
    time: "09:31",
    type: "delivery",
    title: "Load L10355 delivered successfully",
    description: "Delivered to Indianapolis consignee 20 minutes ahead of scheduled appointment.",
  },
  {
    id: "EV-04",
    time: "09:22",
    type: "automation",
    title: "n8n Daily Report generated & archived",
    description: "Automated executive summary compiled for Operations Management.",
  },
  {
    id: "EV-05",
    time: "08:50",
    type: "delay",
    title: "Load L10231 roadside stop reported",
    description: "Marcus Vance logged flat tire inspection near Cincinnati, OH.",
  },
];

export const copilotSampleQueries = [
  "Which loads are likely to be late today?",
  "Show me the carriers with the worst on-time delivery rate this month",
  "What is the procedure when a carrier misses pickup?",
  "What revenue was generated on the Chicago to Dallas corridor?",
  "Find high-risk loads and explain the top SHAP contributing factors",
  "What is our detention billing policy for delays exceeding 2 hours?",
];
